spring.application.name=simupay-backend

#conexão com o banco 'simpay_db'
spring.datasource.url=jdbc:postgresql://localhost:5432/simpay_db
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.drive-class-name=org.postgresql.Drive

#mostra o SQL no terminal (debug)
logging.level.org.springframework.jdbc.core=DEBUG