spring.application.name=simupay-backend
spring.datasource.type=org.apache.tomcat.jdbc.pool.DataSource
# Carrega as variáveis locais do arquivo .env, quando ele existir
spring.config.import=optional:file:.env[.properties]

#conexão com o banco 'simpay_db'
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USER}
spring.datasource.password=${DATABASE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

#mostra o SQL no terminal (debug)
logging.level.org.springframework.jdbc.core=DEBUG

spring.datasource.tomcat.max-wait=3000